export const metadata = {
  title: 'MiamListe',
  description: 'MiamListe By AsuraMoon Generated by Next.js',
}

import { SpeedInsights } from "@vercel/speed-insights/next"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  )
}
