import "./app.css";

export const metadata = {
  title: "MiamListe",
  description: "MiamListe By AsuraMoon Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className="app-root">{children}</body>
    </html>
  );
}
