export const metadata = {
  title: 'MiamListe',
  description: 'MiamListe By AsuraMoon Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
